platform :ios, '17.0'

target 'SMSBridge' do
  use_frameworks! :linkage => :static

  pod 'GoogleWebRTC'
  pod 'Socket.IO-Client-Swift', '~> 16.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EAGER_LINKING'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    end
  end
end
